version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-patch:
        update-types:
          - patch
      npm-minor:
        update-types:
          - minor
    ignore:
      - dependency-name: playwright

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-patch:
        update-types:
          - patch
      actions-minor:
        update-types:
          - minor
